riscv64-linux-gnu-as -c -ggdb -march=rv64ima -mabi=lp64 -o build/src/trap.o src/trap.s
riscv64-linux-gnu-as -c -ggdb -march=rv64ima -mabi=lp64 -o build/test_src/lock.o test_src/lock.s
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/syscall_cpp.d" -Wa,-a,-ad,-alms=build/src/syscall_cpp.lst -o build/src/syscall_cpp.o src/syscall_cpp.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/timer.d" -Wa,-a,-ad,-alms=build/src/timer.lst -o build/src/timer.o src/timer.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/syscalls_c.d" -Wa,-a,-ad,-alms=build/src/syscalls_c.lst -o build/src/syscalls_c.o src/syscalls_c.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/sem.d" -Wa,-a,-ad,-alms=build/src/sem.lst -o build/src/sem.o src/sem.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/main.d" -Wa,-a,-ad,-alms=build/src/main.lst -o build/src/main.o src/main.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/assert.d" -Wa,-a,-ad,-alms=build/src/assert.lst -o build/src/assert.o src/assert.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/kernel.d" -Wa,-a,-ad,-alms=build/src/kernel.lst -o build/src/kernel.o src/kernel.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/usermain.d" -Wa,-a,-ad,-alms=build/src/usermain.lst -o build/src/usermain.o src/usermain.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/thread.d" -Wa,-a,-ad,-alms=build/src/thread.lst -o build/src/thread.o src/thread.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/heapManager.d" -Wa,-a,-ad,-alms=build/src/heapManager.lst -o build/src/heapManager.o src/heapManager.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/consoleManager.d" -Wa,-a,-ad,-alms=build/src/consoleManager.lst -o build/src/consoleManager.o src/consoleManager.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/exceptionHandler.d" -Wa,-a,-ad,-alms=build/src/exceptionHandler.lst -o build/src/exceptionHandler.o src/exceptionHandler.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/src/sched.d" -Wa,-a,-ad,-alms=build/src/sched.lst -o build/src/sched.o src/sched.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/buffer.d" -Wa,-a,-ad,-alms=build/test_src/buffer.lst -o build/test_src/buffer.o test_src/buffer.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/ConsumerProducer_C_API_test.d" -Wa,-a,-ad,-alms=build/test_src/ConsumerProducer_C_API_test.lst -o build/test_src/ConsumerProducer_C_API_test.o test_src/ConsumerProducer_C_API_test.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/ConsumerProducer_CPP_API_test.d" -Wa,-a,-ad,-alms=build/test_src/ConsumerProducer_CPP_API_test.lst -o build/test_src/ConsumerProducer_CPP_API_test.o test_src/ConsumerProducer_CPP_API_test.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/System_Mode_test.d" -Wa,-a,-ad,-alms=build/test_src/System_Mode_test.lst -o build/test_src/System_Mode_test.o test_src/System_Mode_test.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/Threads_C_API_test.d" -Wa,-a,-ad,-alms=build/test_src/Threads_C_API_test.lst -o build/test_src/Threads_C_API_test.o test_src/Threads_C_API_test.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/ThreadSleep_C_API_test.d" -Wa,-a,-ad,-alms=build/test_src/ThreadSleep_C_API_test.lst -o build/test_src/ThreadSleep_C_API_test.o test_src/ThreadSleep_C_API_test.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/buffer_CPP_API.d" -Wa,-a,-ad,-alms=build/test_src/buffer_CPP_API.lst -o build/test_src/buffer_CPP_API.o test_src/buffer_CPP_API.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/Threads_CPP_API_test.d" -Wa,-a,-ad,-alms=build/test_src/Threads_CPP_API_test.lst -o build/test_src/Threads_CPP_API_test.o test_src/Threads_CPP_API_test.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/userMain.d" -Wa,-a,-ad,-alms=build/test_src/userMain.lst -o build/test_src/userMain.o test_src/userMain.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/printing.d" -Wa,-a,-ad,-alms=build/test_src/printing.lst -o build/test_src/printing.o test_src/printing.cpp
riscv64-linux-gnu-g++ -c -Wall -Werror -Og -ggdb -nostdlib -std=c++11 -march=rv64ima -mabi=lp64 -mcmodel=medany -mno-relax -fno-omit-frame-pointer -ffreestanding -fno-common -fno-rtti -fno-threadsafe-statics -I./lib -I./h -fno-stack-protector -D DEBUG_PRINT=0 -MMD -MP -MF"build/test_src/ConsumerProducer_CPP_Sync_API_test.d" -Wa,-a,-ad,-alms=build/test_src/ConsumerProducer_CPP_Sync_API_test.lst -o build/test_src/ConsumerProducer_CPP_Sync_API_test.o test_src/ConsumerProducer_CPP_Sync_API_test.cpp
riscv64-linux-gnu-ld -z max-page-size=4096 --script kernel.ld -o kernel  build/src/trap.o build/test_src/lock.o  build/src/syscall_cpp.o build/src/timer.o build/src/syscalls_c.o build/src/sem.o build/src/main.o build/src/assert.o build/src/kernel.o build/src/usermain.o build/src/thread.o build/src/heapManager.o build/src/consoleManager.o build/src/exceptionHandler.o build/src/sched.o build/test_src/buffer.o build/test_src/ConsumerProducer_C_API_test.o build/test_src/ConsumerProducer_CPP_API_test.o build/test_src/System_Mode_test.o build/test_src/Threads_C_API_test.o build/test_src/ThreadSleep_C_API_test.o build/test_src/buffer_CPP_API.o build/test_src/Threads_CPP_API_test.o build/test_src/userMain.o build/test_src/printing.o build/test_src/ConsumerProducer_CPP_Sync_API_test.o --library-path . --library=:lib/hw.lib --library-path . --library=:lib/hw.lib
riscv64-linux-gnu-objdump --source kernel > kernel.asm
qemu-system-riscv64 -machine virt -bios none -kernel kernel -m 128M -smp 1 -nographic